<?php
/**
 * Seovela LLMS Txt Module
 *
 * Serves a custom llms.txt file to guide AI models
 * with your most important posts, terms, and content.
 *
 * @package Seovela
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Seovela LLMS Txt Class
 */
class Seovela_Llms_Txt {

    /**
     * Get instance (singleton)
     *
     * @var Seovela_Llms_Txt
     */
    private static $instance = null;

    /**
     * Get singleton instance
     *
     * @return Seovela_Llms_Txt
     */
    public static function get_instance() {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Constructor
     */
    private function __construct() {
        add_action( 'init', array( $this, 'add_rewrite_rules' ) );
        add_action( 'template_redirect', array( $this, 'serve_llms_txt' ) );
    }

    /**
     * Add rewrite rules for llms.txt
     */
    public function add_rewrite_rules() {
        add_rewrite_rule( '^llms\.txt$', 'index.php?seovela_llms_txt=1', 'top' );
        add_filter( 'query_vars', array( $this, 'add_query_vars' ) );
    }

    /**
     * Add query vars
     *
     * @param array $vars Query vars.
     * @return array
     */
    public function add_query_vars( $vars ) {
        $vars[] = 'seovela_llms_txt';
        return $vars;
    }

    /**
     * Serve llms.txt output
     */
    public function serve_llms_txt() {
        if ( ! get_query_var( 'seovela_llms_txt' ) ) {
            return;
        }

        // Allow other plugins/themes to hook before output.
        do_action( 'seovela_before_llms_txt_output' );

        header( 'Content-Type: text/plain; charset=utf-8' );
        echo $this->generate_llms_txt();

        do_action( 'seovela_after_llms_txt_output' );

        exit;
    }

    /**
     * Generate llms.txt content
     *
     * This is intentionally simple plain text that AI models
     * can easily parse. Developers can filter the output.
     *
     * @return string
     */
    public function generate_llms_txt() {
        $lines   = array();
        $home_url = home_url( '/' );

        $lines[] = '# llms.txt generated by Seovela';
        $lines[] = '# Learn more: https://seovela.com';
        $lines[] = '';
        $lines[] = 'site: ' . esc_url_raw( $home_url );
        $lines[] = 'generated: ' . gmdate( 'c' );
        $lines[] = '';

        // Get settings (use new options or fall back to sitemap settings)
        $post_types = get_option( 'seovela_llms_txt_post_types', get_option( 'seovela_sitemap_post_types', array( 'post', 'page' ) ) );
        $taxonomies = get_option( 'seovela_llms_txt_taxonomies', get_option( 'seovela_sitemap_taxonomies', array() ) );
        $limit = get_option( 'seovela_llms_txt_limit', 50 );
        $additional_content = get_option( 'seovela_llms_txt_additional_content', '' );

        // Add additional content at the top if provided
        if ( ! empty( $additional_content ) ) {
            $lines[] = trim( $additional_content );
            $lines[] = '';
        }

        // Posts & pages (based on settings).
        $lines[] = '# Important content: posts & pages';

        if ( ! empty( $post_types ) && is_array( $post_types ) ) {
            $post_query = new WP_Query(
                array(
                    'post_type'      => $post_types,
                    'posts_per_page' => intval( $limit ),
                    'post_status'    => 'publish',
                    'orderby'        => 'modified',
                    'order'          => 'DESC',
                    'no_found_rows'  => true,
                    'fields'         => 'ids',
                )
            );

            if ( $post_query->have_posts() ) {
                foreach ( $post_query->posts as $post_id ) {
                    // Skip if explicitly noindex.
                    if ( get_post_meta( $post_id, '_seovela_noindex', true ) ) {
                        continue;
                    }

                    $url   = get_permalink( $post_id );
                    $title = get_the_title( $post_id );

                    // Detect "pillar" or key content via sticky flag or custom meta (if used).
                    $is_sticky   = is_sticky( $post_id );
                    $is_pillar   = (bool) get_post_meta( $post_id, '_seovela_pillar', true );
                    $importance  = $is_pillar || $is_sticky ? 'high' : 'normal';

                    $line = 'post: ' . esc_url_raw( $url );
                    $line .= ' | title="' . sanitize_text_field( $title ) . '"';
                    $line .= ' | importance=' . $importance;

                    $lines[] = $line;
                }
            }

            wp_reset_postdata();
        }

        $lines[] = '';
        $lines[] = '# Taxonomy terms (topics, categories, tags)';

        if ( ! empty( $taxonomies ) && is_array( $taxonomies ) ) {
            foreach ( $taxonomies as $taxonomy ) {
                $terms = get_terms(
                    array(
                        'taxonomy'   => $taxonomy,
                        'hide_empty' => true,
                        'number'     => intval( $limit ),
                    )
                );

                if ( is_wp_error( $terms ) || empty( $terms ) ) {
                    continue;
                }

                foreach ( $terms as $term ) {
                    $url   = get_term_link( $term );
                    if ( is_wp_error( $url ) ) {
                        continue;
                    }

                    $line  = 'term: ' . esc_url_raw( $url );
                    $line .= ' | taxonomy=' . sanitize_key( $taxonomy );
                    $line .= ' | name="' . sanitize_text_field( $term->name ) . '"';

                    $lines[] = $line;
                }
            }
        }

        $lines[] = '';
        $lines[] = '# You can customize this output using the seovela_llms_txt_content filter.';

        $content = implode( "\n", $lines );

        /**
         * Filter the llms.txt content before output.
         *
         * @param string $content Generated llms.txt content.
         */
        return apply_filters( 'seovela_llms_txt_content', $content );
    }
}


